import {CardMin} from '../../interfaces/card';

export const units: CardMin[] = [
    {
        id: 'neutral_c_u_0',
        name: 'Barrel',
        image: 'barrel',
        mana: 2,
        offense: 1,
        defense: 0,
        health: 3,
    },
    {
        id: 'neutral_c_u_1',
        name: 'Mushroom',
        image: 'mushroom',
        mana: 3,
        offense: 3,
        defense: 2,
        health: 1,
    },
    {
        id: 'neutral_c_u_2',
        name: 'Sign',
        image: 'sign',
        mana: 2,
        offense: 1,
        defense: 0,
        health: 4,
    },
    {
        id: 'neutral_c_u_3',
        name: 'Waggon',
        image: 'waggon',
        mana: 3,
        offense: 1,
        defense: 0,
        health: 5,
    },
    {
        id: 'neutral_c_u_4',
        name: 'Wood Spider',
        image: 'wood_spider',
        mana: 4,
        offense: 3,
        defense: 2,
        health: 3,
    },
    {
        id: 'neutral_c_u_5',
        name: 'Crab',
        image: 'crab',
        mana: 3,
        offense: 3,
        defense: 1,
        health: 2,
    },
    {
        id: 'neutral_c_u_6',
        name: 'Bird',
        image: 'bird',
        mana: 4,
        offense: 3,
        defense: 1,
        health: 4,
    },
    {
        id: 'neutral_c_u_7',
        name: 'Frog',
        image: 'frog',
        mana: 3,
        offense: 2,
        defense: 1,
        health: 3,
    },
    {
        id: 'neutral_c_u_8',
        name: 'Well',
        image: 'well',
        mana: 4,
        offense: 2,
        defense: 1,
        health: 5,
    },
    {
        id: 'neutral_c_u_9',
        name: 'Honey',
        image: 'honey',
        mana: 2,
        offense: 2,
        defense: 1,
        health: 1,
    },
];