import {CardMin} from '../../interfaces/card';

export const units: CardMin[] = [
    {
        id: 'neutral_e_u_0',
        name: 'Brodo',
        image: 'brodo',
        mana: 12,
        offense: 13,
        defense: 6,
        health: 11,
    },
    {
        id: 'neutral_e_u_1',
        name: 'Boar',
        image: 'boar',
        mana: 9,
        offense: 10,
        defense: 6,
        health: 7,
    },
    {
        id: 'neutral_e_u_2',
        name: 'Predator',
        image: 'predator',
        mana: 12,
        offense: 15,
        defense: 8,
        health: 7,
    },
    {
        id: 'neutral_e_u_3',
        name: 'Naga',
        image: 'naga',
        mana: 15,
        offense: 15,
        defense: 7,
        health: 16,
    },
    {
        id: 'neutral_e_u_4',
        name: 'Ghoul',
        image: 'ghoul',
        mana: 12,
        offense: 13,
        defense: 6,
        health: 11,
    },
    {
        id: 'neutral_e_u_5',
        name: 'Insect',
        image: 'insect',
        mana: 9,
        offense: 9,
        defense: 5,
        health: 9,
    },
    {
        id: 'neutral_e_u_6',
        name: 'Swordsman',
        image: 'swordsman',
        mana: 11,
        offense: 12,
        defense: 7,
        health: 9,
    },
    {
        id: 'neutral_e_u_7',
        name: 'Ancient Monster',
        image: 'ancient_monster',
        mana: 8,
        offense: 6,
        defense: 2,
        health: 12,
    },
    {
        id: 'neutral_e_u_8',
        name: 'Meteor',
        image: 'meteor',
        mana: 10,
        offense: 13,
        defense: 6,
        health: 6,
    },
    {
        id: 'neutral_e_u_9',
        name: 'Fireball',
        image: 'fireball',
        mana: 10,
        offense: 13,
        defense: 8,
        health: 4,
    },
];