import {CardMin} from '../../interfaces/card';

export const units: CardMin[] = [
    {
        id: 'neutral_l_u_0',
        name: 'Portal',
        image: 'portal',
        mana: 14,
        offense: 21,
        defense: 12,
        health: 6,
    },
    {
        id: 'neutral_l_u_1',
        name: 'Yeti',
        image: 'yeti',
        mana: 14,
        offense: 14,
        defense: 7,
        health: 18,
    },
    {
        id: 'neutral_l_u_2',
        name: 'Demon',
        image: 'demon',
        mana: 17,
        offense: 18,
        defense: 6,
        health: 23,
    },
    {
        id: 'neutral_l_u_3',
        name: 'Star fire',
        image: 'star_fire',
        mana: 15,
        offense: 21,
        defense: 11,
        health: 9,
    },
    {
        id: 'neutral_l_u_4',
        name: 'Telekinesis',
        image: 'telekinesis',
        mana: 12,
        offense: 17,
        defense: 10,
        health: 6,
    },
    {
        id: 'neutral_l_u_5',
        name: 'Cataclysm',
        image: 'cataclysm',
        mana: 15,
        offense: 15,
        defense: 9,
        health: 17,
    },
    {
        id: 'neutral_l_u_6',
        name: 'Mercenary',
        image: 'mercenary',
        mana: 10,
        offense: 9,
        defense: 4,
        health: 15,
    },
    {
        id: 'neutral_l_u_7',
        name: 'Golem',
        image: 'golem',
        mana: 9,
        offense: 9,
        defense: 4,
        health: 12,
    },
    {
        id: 'neutral_l_u_8',
        name: 'Heart',
        image: 'heart',
        mana: 16,
        offense: 16,
        defense: 5,
        health: 23,
    },
    {
        id: 'neutral_l_u_9',
        name: 'Invisibility',
        image: 'invisibility',
        mana: 16,
        offense: 6,
        defense: 5,
        health: 30,
    },
];