import {CardMin} from '../../interfaces/card';

export const units: CardMin[] = [
    {
        id: 'neutral_r_u_0',
        name: 'Egg',
        image: 'egg',
        mana: 6,
        offense: 6,
        defense: 4,
        health: 4,
    },
    {
        id: 'neutral_r_u_1',
        name: 'Barracks',
        image: 'barracks',
        mana: 6,
        offense: 4,
        defense: 2,
        health: 8,
    },
    {
        id: 'neutral_r_u_2',
        name: 'Kobold',
        image: 'kobold',
        mana: 8,
        offense: 6,
        defense: 4,
        health: 8,
    },
    {
        id: 'neutral_r_u_3',
        name: 'Carrot',
        image: 'carrot',
        mana: 2,
        offense: 2,
        defense: 1,
        health: 2,
    },
    {
        id: 'neutral_r_u_4',
        name: 'Fear',
        image: 'fear',
        mana: 6,
        offense: 7,
        defense: 4,
        health: 3,
    },
    {
        id: 'neutral_r_u_5',
        name: 'Sight',
        image: 'sight',
        mana: 6,
        offense: 8,
        defense: 5,
        health: 1,
    },
    {
        id: 'neutral_r_u_6',
        name: 'Imp',
        image: 'imp',
        mana: 7,
        offense: 5,
        defense: 3,
        health: 8,
    },
    {
        id: 'neutral_r_u_7',
        name: 'Adventurer',
        image: 'adventurer',
        mana: 6,
        offense: 5,
        defense: 3,
        health: 6,
    },
    {
        id: 'neutral_r_u_8',
        name: 'Artifact',
        image: 'artifact',
        mana: 5,
        offense: 6,
        defense: 4,
        health: 1,
    },
    {
        id: 'neutral_r_u_9',
        name: 'Fisher',
        image: 'fisher',
        mana: 5,
        offense: 6,
        defense: 4,
        health: 1,
    },
    {
        id: 'neutral_r_u_10',
        name: 'Sea Dog',
        image: 'sea_dog',
        mana: 6,
        offense: 6,
        defense: 3,
        health: 5,
    },
    {
        id: 'neutral_r_u_11',
        name: 'To Ku',
        image: 'to_ku',
        mana: 5,
        offense: 4,
        defense: 2,
        health: 5,
    },
    {
        id: 'neutral_r_u_12',
        name: 'Frost Weapon',
        image: 'frost_weapon',
        mana: 6,
        offense: 7,
        defense: 3,
        health: 4,
    },
    {
        id: 'neutral_r_u_13',
        name: 'Lizard',
        image: 'lizard',
        mana: 3,
        offense: 3,
        defense: 2,
        health: 2,
    },
    {
        id: 'neutral_r_u_14',
        name: 'Diver',
        image: 'diver',
        mana: 6,
        offense: 5,
        defense: 3,
        health: 6,
    },
];